'use client';

import { useState } from 'react';
import { DecisionBrief } from '@/lib/types';
import { AGENTS, AGENT_ORDER } from '@/lib/agents';

interface Props {
  question: string;
  agentContents: Record<string, string>;
  brief: DecisionBrief | null;
}

export default function ShareBar({ question, agentContents, brief }: Props) {
  const [copied, setCopied] = useState(false);

  function buildText(): string {
    const lines = [
      `AI WAR ROOM — Decision Debate`,
      `==============================`,
      `Question: ${question}`,
      ``,
    ];
    for (const role of AGENT_ORDER) {
      const agent = AGENTS[role];
      const content = agentContents[role];
      if (content) {
        lines.push(`[${agent.emoji} ${agent.name}]`);
        lines.push(content);
        lines.push('');
      }
    }
    if (brief) {
      lines.push('DECISION BRIEF');
      lines.push('--------------');
      lines.push(`Summary: ${brief.summary}`);
      lines.push(`Recommendation: ${brief.recommendation}`);
      lines.push(`Confidence: ${brief.confidence}%`);
      if (brief.risks?.length) lines.push(`Risks: ${brief.risks.join(' | ')}`);
    }
    lines.push('', 'Generated by AI War Room — github.com/EphraimIndugubilli/ai-war-room');
    return lines.join('\n');
  }

  async function copy() {
    await navigator.clipboard.writeText(buildText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function download() {
    const blob = new Blob([buildText()], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `war-room-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="flex items-center gap-2 mt-2">
      <button onClick={copy}
        className="flex items-center gap-2 text-xs px-3 py-1.5 rounded-lg border transition-all"
        style={{ borderColor: 'rgba(255,255,255,0.1)', background: 'rgba(255,255,255,0.03)', color: copied ? '#10B981' : '#94a3b8' }}>
        {copied ? '✓ Copied' : '⎘ Copy debate'}
      </button>
      <button onClick={download}
        className="flex items-center gap-2 text-xs px-3 py-1.5 rounded-lg border transition-all"
        style={{ borderColor: 'rgba(255,255,255,0.1)', background: 'rgba(255,255,255,0.03)', color: '#94a3b8' }}>
        ⬇ Export .txt
      </button>
    </div>
  );
}
